name: "Build and Deploy"

on:
  push:
    tags:
      - "*.*.*"

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Type check
        run: npx tsc --noEmit
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Build and submit
        run: eas build --platform ios --auto-submit --non-interactive --no-wait
        env:
          APP_VERSION: ${{ github.ref_name }}
